apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-deployment-v1
  namespace: default
  labels:
    app: canary-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: canary-app

  template:
    metadata:
      labels:
        app: canary-app
    spec:
      containers:
        - name: canary-app-v1
          image: mannasuman134/canary-app:v1
          resources:
            requests:
              cpu: '10m'
              memory: '150Mi'
            limits:
              cpu: '50m'
              memory: '400Mi'
          imagePullPolicy: Always
      restartPolicy: Always
